version: '3.3'
services:

# ENGINE-MANAGER
  engine-manager:
    image: registry.gitlab.com/benchpilot/benchpilot-sdk/linc-engine-cluster:storm
    hostname: engine-manager
    restart: on-failure
    ports:
      - 6627:6627
    networks:
      - benchPilot
    command: ["/bin/bash", "-c", "./stream-bench.sh START_MANAGER && sleep infinity"]
    deploy:
      placement:
        constraints:
          - node.role==manager

# ENGINE-CLIENT
  engine-client:
    image: registry.gitlab.com/benchpilot/benchpilot-sdk/linc-engine-client:storm
    hostname: engine-client
    restart: on-failure
    ports:
      - 5000:5000
    networks:
      - benchPilot
    environment:
      - NIMBUS_SEEDS=10.16.3.91
      - NIMBUS_THRIFT_PORT=6627
      - engine=storm
      - ui_hostname=10.16.3.91
      - ui_port=8080
      - workload=marketing-campaign
    depends_on:
      - engine-manager
    deploy:
      placement:
        constraints:
          - node.role==manager

# ENGINE-WORKER_0
  engine-worker_0:
    image: registry.gitlab.com/benchpilot/benchpilot-sdk/linc-engine-cluster:storm-arm
    hostname: engine-worker_0
    restart: on-failure
    networks:
      - benchPilot
    command: ["/bin/bash", "-c", "./stream-bench.sh START_WORKER && sleep infinity"]
    depends_on:
      - engine-manager
    deploy:
      placement:
        constraints:
          - node.hostname==raspberrypi3

# ENGINE-WORKER_1
  engine-worker_1:
    image: registry.gitlab.com/benchpilot/benchpilot-sdk/linc-engine-cluster:storm-arm
    hostname: engine-worker_1
    restart: on-failure
    networks:
      - benchPilot
    command: ["/bin/bash", "-c", "./stream-bench.sh START_WORKER && sleep infinity"]
    depends_on:
      - engine-manager
    deploy:
      placement:
        constraints:
          - node.hostname==raspberrypi0

# STORM-UI
  storm-ui:
    image: registry.gitlab.com/benchpilot/benchpilot-sdk/linc-engine-cluster:storm
    hostname: storm-ui
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - benchPilot
    command: ["/bin/bash", "-c", "./stream-bench.sh START_UI && sleep infinity"]
    depends_on:
      - engine-manager
    deploy:
      placement:
        constraints:
          - node.role==manager

# ZOOKEEPER
  zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: zookeeper
    restart: on-failure
    ports:
      - 2181:2181
    networks:
      - benchPilot
    deploy:
      placement:
        constraints:
          - node.role==manager

# KAFKA
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    hostname: kafka
    restart: on-failure
    ports:
      - 9092:9092
      - 9094:9094
    networks:
      - benchPilot
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://10.16.3.91:9094
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_CREATE_TOPICS="ad-events:2:1"
      - KAFKA_NUM_PARTITIONS=2
    depends_on:
      - zookeeper
    deploy:
      placement:
        constraints:
          - node.role==manager

# REDIS
  redis:
    image: bitnami/redis:6.0.10
    hostname: redis
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - benchPilot
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    deploy:
      placement:
        constraints:
          - node.role==manager
networks:
  benchPilot:
    external: true



